# Configuración de la aplicación
spring.application.name=inventory-service
server.port=8081

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.jlsolutions.commons.ProductEvent
spring.kafka.consumer.properties.session.timeout.ms=30000
spring.kafka.consumer.properties.heartbeat.interval.ms=10000
spring.kafka.consumer.properties.retry.backoff.ms=100

# Logging para debug
#logging.level.org.apache.kafka.clients.NetworkClient=DEBUG
#logging.level.org.apache.kafka=DEBUG

#Database
spring.data.mongodb.uri=mongodb+srv://julianmarcelolopez:C3sK4Edcxq65drld@cluster0.k4vau.mongodb\
  .net/inventorydb?retryWrites=true&w=majority


